"""empty message

Revision ID: facb1bcd09e3
Revises: 5d33c12ba31b
Create Date: 2025-04-06 14:35:53.144340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'facb1bcd09e3'
down_revision: Union[str, None] = '5d33c12ba31b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('offer_service_types',
    sa.Column('offer_id', sa.BigInteger(), nullable=False),
    sa.Column('service_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_type_id'], ['service_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('offer_id', 'service_type_id')
    )
    op.drop_column('offers', 'age')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_table('offer_service_types')
    op.drop_table('service_types')
    # ### end Alembic commands ###
